trigger:
- main

stages:
- stage: Build
  displayName: 'Build and Push Docker image'
  jobs:
  - job: Build
    displayName: 'Build'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: 'Build and push Docker image'
      inputs:
        command: 'buildAndPush'
        containerRegistry: 'YourDockerRegistryConnection'  # Azure Container Registry connection
        repository: 'yourdockerrepository'  # Docker repository name
        dockerfile: '**/Dockerfile'
        tags: 'latest'

- stage: Deploy
  displayName: 'Deploy to Azure Container Instances'
  dependsOn: Build
  jobs:
  - deployment: Deploy
    displayName: 'Deploy'
    environment: 'YourEnvironmentName'  # Environment name for Azure Container Instances
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureCLI@2
            displayName: 'Deploy to Azure Container Instances'
            inputs:
              azureSubscription: 'YourAzureSubscription'  # Azure subscription name
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az container create --resource-group YourResourceGroup --name YourContainerName --image yourdockerrepository.azurecr.io/yourimage:latest --cpu 1 --memory 1 --registry-login-server yourdockerregistry.azurecr.io --registry-username $(acrServicePrincipalId) --registry-password $(acrServicePrincipalPassword)
